[package]
name = "waku-lightpush"
description = "19/WAKU2-LIGHTPUSH v3 (Milestone 4)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
waku-core = { workspace = true }
prost = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
libp2p = { workspace = true, features = ["request-response"] }
