[package]
name = "waku-node"
description = "Composes all Waku protocol behaviours into a node (peer manager, config, lifecycle)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
waku-core = { workspace = true }
waku-enr = { workspace = true }
waku-discv5 = { workspace = true }
waku-relay = { workspace = true }
waku-rln = { workspace = true }
waku-store = { workspace = true }
waku-filter = { workspace = true }
waku-lightpush = { workspace = true }
waku-peer-exchange = { workspace = true }
waku-metadata = { workspace = true }

thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
prost = { workspace = true }
libp2p = { workspace = true, features = [
    "tcp",
    "tokio",
    "noise",
    "yamux",
    "macros",
    "identify",
    "gossipsub",
    "request-response",
] }

[dev-dependencies]
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
